model:
  name: housing_price_model
  version: '1'
  stage: Staging
  best_model: GradientBoosting
  parameters:
    learning_rate: 0.07009925729923229
    min_samples_split: 17
    subsample: 0.8182379694901705
    n_estimators: 418
    max_features: null
    max_depth: 8
    min_samples_leaf: 2
    random_state: 42
  r2_score: 0.8449426367335227
  mae: 29325.176069463007
  rmse: 45076.44184790461
  mape: 16.54733293504644
  target_variable: median_house_value
  num_features: 14
  feature_columns:
  - longitude
  - latitude
  - housing_median_age
  - total_rooms
  - total_bedrooms
  - population
  - households
  - median_income
  - ocean_proximity_<1H OCEAN
  - ocean_proximity_INLAND
  - ocean_proximity_ISLAND
  - ocean_proximity_NEAR BAY
  - ocean_proximity_NEAR OCEAN
  - cluster_label
  mlflow_run_id: c843b994ab264991acd9277a61135dbf
  mlflow_model_uri: runs:/c843b994ab264991acd9277a61135dbf/model
  gcs_model_uri: gs://mlops-practices-wb-cap2-end_to_end/models/07-registration/housing_price_model.pkl
  local_path: models/trained/housing_price_model.pkl
  sweep_id: aadnfqki
