model:
  best_model: RandomForest
  feature_columns:
  - longitude
  - latitude
  - housing_median_age
  - total_rooms
  - total_bedrooms
  - population
  - households
  - median_income
  - ocean_proximity_NEAR BAY
  - cluster_label
  local_path: models/trained/housing_price_model.pkl
  mae: 42884.55161103307
  mape: 23.961431911283096
  mlflow_model_uri: runs:/4c5f3f2d72654883bbd769cad318ba3c/model
  mlflow_run_id: 4c5f3f2d72654883bbd769cad318ba3c
  name: housing_price_model
  num_features: 10
  parameters:
    max_depth: 23
    max_features: log2
    min_samples_leaf: 9
    min_samples_split: 9
    n_estimators: 128
    random_state: 42
  r2_score: 0.37576587326740685
  rmse: 72643.12203666329
  stage: Staging
  sweep_id: f73ao31m
  target_variable: median_house_value
  version: '10'
